name: Comment Floodgate
on: issue_comment
jobs:
  floodgate:
    runs-on: ubuntu-latest
    steps:
    - uses: js-choi/github-comment-floodgate@v2
      with:
        minutes-in-period: 60
        # This number is how many comments are allowed per period per issue.
        max-comments-per-period: 12
